name: sa_babi
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.5.0=py_0
  - astor=0.7.1=py_0
  - bzip2=1.0.6=1
  - c-ares=1.14.0=h470a237_0
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2018.8.24=py36_1001
  - clangdev=6.0.1=default_1
  - cycler=0.10.0=py_1
  - freetype=2.9.1=h6debe1e_4
  - gast=0.2.0=py_0
  - grpcio=1.14.1=py36hd60e7a3_0
  - h5py=2.8.0=py36h7eb728f_2
  - hdf5=1.10.2=hc401514_2
  - icu=58.2=hfc679d8_0
  - keras=2.2.3=py36_0
  - keras-applications=1.0.4=py_1
  - keras-preprocessing=1.0.2=py_1
  - kiwisolver=1.0.1=py36h2d50403_2
  - libcxx=6.0.1=0
  - libffi=3.2.1=hfc679d8_5
  - libgpuarray=0.7.6=h470a237_3
  - libiconv=1.15=h470a237_3
  - libpng=1.6.35=ha92aebf_2
  - libprotobuf=3.6.0=hd28b015_0
  - libxml2=2.9.8=h422b904_5
  - llvm-meta=6.0.1=0
  - llvmdev=6.0.1=hf8ce74a_2
  - mako=1.0.7=py_1
  - markdown=2.6.11=py_0
  - markupsafe=1.0=py36h470a237_1
#  - matplotlib=3.0.0=py36h45c993b_1
  - mkl_fft=1.0.6=py36_0
  - mkl_random=1.0.1=py36_0
  - ncurses=6.1=hfc679d8_1
  - openblas=0.2.20=8
  - openssl=1.0.2p=h470a237_0
  - pandas=0.23.4=py36hf8a1672_0
  - pip=18.0=py36_1001
  - protobuf=3.6.0=py36hfc679d8_0
  - pygpu=0.7.6=py36h7eb728f_0
  - pyparsing=2.2.2=py_0
  - python=3.6.6=h5001a0f_0
  - python-dateutil=2.7.3=py_0
  - pytz=2018.5=py_0
  - pyyaml=3.13=py36h470a237_1
  - readline=7.0=haf1bffa_1
  - setuptools=40.4.0=py36_1000
  - six=1.11.0=py36_1
  - sqlite=3.25.2=hb1c47c0_0
  - tensorboard=1.10.0=py36_0
  - tensorflow=1.10.0=py36_0
  - termcolor=1.1.0=py_2
  - theano=1.0.3=py36_0
  - tk=8.6.8=ha92aebf_0
  - tornado=5.1.1=py36h470a237_0
  - werkzeug=0.14.1=py_0
  - wheel=0.32.0=py36_1000
  - xz=5.2.4=h470a237_1
  - yaml=0.1.7=h470a237_1
  - zlib=1.2.11=h470a237_3
  - blas=1.0=mkl
  - intel-openmp=2019.0=118
  - libgfortran=3.0.1=h93005f0_2
  - libopenblas=0.3.3=hdc02c5d_3
  - mkl=2019.0=118
  - numpy=1.15.2=py36h6a91979_0
  - numpy-base=1.15.2=py36h8a80b8c_0
  - scikit-learn=0.20.0=py36h4f467ca_1
  - scipy=1.1.0=py36h28f7352_1
prefix: /Users/nmvanhoudnos/anaconda3/envs/sa_babi
